### ISSUE TITLE
Missing pre-reqs from Readme.md

### ISSUE THREAD

**Issue by markstinson** [mhiramat/mincs#5]
While reviewing code on github regarding feasibility for my project, I noticed that if someone is importing a Docker image, the user will need to have the optional components installed:
- docker # obviously
- jq # sed-like for json - https://github.com/stedolan/jq/ ; docs: https://stedolan.github.io/jq/

**Comment by mhiramat** [comment]
Thank you for reporting!
I've update README.md according to your report.
