### ISSUE TITLE
The "unshare" command doesn't recognize the '-p' and '-f' flags on Linux Mint

### ISSUE THREAD

**Issue by ivandavidov** [mhiramat/mincs#6]
I recently cloned your `mincs` repository and successfully installed the scripts. However, when I executed `minc` I got the following output:

```
ivan@vbox64 ~/mincs $ minc
unshare: invalid option -- 'p'

Usage:
 unshare [options] <program> [args...]

Options:
 -h, --help        usage information (this)
 -m, --mount       unshare mounts namespace
 -u, --uts         unshare UTS namespace (hostname etc)
 -i, --ipc         unshare System V IPC namespace
 -n, --net         unshare network namespace

For more information see unshare(1).
ivan@vbox64 ~/mincs $ 
```

The issue is that `unshare` is used in the `minc-exec` script where we see the following command:

`$IP_NETNS unshare -iumpf $LIBEXEC/`basename $0` "$@"`

As you can see, the `-p` and `-f` flags are expected but on `Linux Mint` these flags are not supported. I checked your [BusyBox patch](https://github.com/mhiramat/boot2minc/blob/master/src/patches/busybox/unshare-add-unshare-support.patch) and I see that all these flags (and even more) are supported there. I guess I can easily rebuild BusyBox and use your applet instead of my `unshare` binary which would solve the issue. However, this is not what the [Pre-requisites](https://github.com/mhiramat/mincs#pre-requisites) say:

`
Or, busybox + unshare patch :)
`

So, my expectation was that the `minc` script is supposed to work fine **without** BusyBox if the `unshare` binary is present. Please correct me if my understanding here is not right.

My question in a nutshell - what is the proper way to run `minc` without using `BusyBox + unshare` patch?

**Comment by mhiramat** [comment]
Thank you for reporting. It seems that your unshare command is too old for minc.

Actually, -p (pid namespace) and -f (fork) has been implemented 2013 on util-linux.
so, you need util-linux >= v2.23. I will add this to README.md.

**Comment by mhiramat** [comment]
Oops, the actual version is v2.24 and it is already described in README.md.
