### ISSUE TITLE
The command "marten import <DIR>" doesn't work properly on BusyBox

### ISSUE THREAD

**Issue by ivandavidov** [mhiramat/mincs#7]
Assuming we have `/some/root/dir` and we want to import it as new image, we should be using this command:

`marten import /some/root/dir`

However, on BusyBox this will fail because ``libexec/minc-farm'' contains the following code on line 58:

`cp -ab $1 $BASEDIR/root`

Note that the `b` option is not supported on BusyBox. Import is successful after manual removal of the `b` option in the `minc-farm` script.

**Comment by mhiramat** [comment]
Thank you for reporting! I'll remove -b option then. it may not be needed.
