### ISSUE TITLE
[ermine enhancement] The 'unshare' patch might not be necessary with BusyBox 1.25.1

### ISSUE THREAD

**Issue by ivandavidov** [mhiramat/mincs#9]
Hello,

My recent experiments with the latest stable BusyBox version (that is version 1.25.1) concluded that I don't really need to apply the `'unshare`' patch since this particular applet and all necessary options/flags have been implemented.

https://git.busybox.net/busybox/log/?qt=grep&q=unshare

**Comment by mhiramat** [comment]
Thanks for reporting!
Right, I also found that when I'm re-implementing ermine build script :)
